version: '3.8'
services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: equilibrar_user
      POSTGRES_PASSWORD: equilibrar_password
      POSTGRES_DB: erp_equilibrar_unified
    ports:
      - '5433:5432'
    volumes:
      - equilibrar_db_data:/var/lib/postgresql/data

volumes:
  equilibrar_db_data:
