

export { Resumen } from './Resumen';
export { Agenda } from './Agenda';
export { Servicios } from './Servicios';
export { Programas } from './Programas';
export { Tratamientos } from './Tratamientos';
export { Cursos } from './Cursos';
export { Usuarios } from './Usuarios';
export { Pagos } from './Pagos';
export { Sucursales } from './Sucursales';
export { TestRFAI } from './TestRFAI';
export { DB } from './DB';
export { Ajustes } from './Ajustes';
export { Auditoria } from './Auditoria';
export { Login } from './Login';
export { default as CRM } from './CRM';
export { default as Whatsapp } from './Whatsapp';
export { default as Bitacoras } from './Bitacoras';
export { default as Chat } from './Chat';
export { default as Ventas } from './Ventas';
export { default as Productos } from './Productos';
export { default as ClientDashboard } from './ClientDashboard';
export { default as ClientProgress } from './ClientProgress';
export { default as Pacientes } from './Pacientes';
export { default as FichasClinicas } from './FichasClinicas';
export { CuentasCobrar } from './CuentasCobrar';
export { CuentasPagar } from './CuentasPagar';
export { Tesoreria } from './Tesoreria';
export { TrabajadoresPlanta } from './TrabajadoresPlanta';
export { Honorarios } from './Honorarios';
export { default as AgenteVirtual } from './AgenteVirtual';
export { default as TestIA } from './TestIA';
export { default as TestWhatsapp } from './TestWhatsapp';
export { default as Consultas } from './Consultas';
export { default as Postventa } from './Postventa';
